### ISSUE TITLE
qdrant_client.http.exceptions.ResponseHandlingException: [Errno -2] Name or service not known

### ISSUE THREAD

**Issue by cyrilzakka** [qdrant/qdrant-client#112]
Hello,

I have a local setup as follows:
```
database = QdrantClient(host=settings().HOST, port=6333, api_key=settings().QDRANT_API)
```
where `HOST` and `QDRANT` are defined in a `dotenv` file where HOST points to a QDRANT cloud  instance 'https://***.****.aws.cloud.qdrant.io'. This works great when initializing the db locally using fastAPI with:
```
uvicorn main:app --reload 
```

As soon as I try deploying on fly.io I get the following error:
```
2023-02-21T05:19:03Z   [info]httpx.ConnectError: [Errno -2] Name or service not known
2023-02-21T05:19:03Z   [info]During handling of the above exception, another exception occurred:
2023-02-21T05:19:03Z   [info]Traceback (most recent call last):
2023-02-21T05:19:03Z   [info]  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 671, in lifespan
2023-02-21T05:19:03Z   [info]    async with self.lifespan_context(app):
2023-02-21T05:19:03Z   [info]  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 566, in __aenter__
2023-02-21T05:19:03Z   [info]    await self._router.startup()
2023-02-21T05:19:03Z   [info]  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 648, in startup
2023-02-21T05:19:03Z   [info]    await handler()
2023-02-21T05:19:03Z   [info]  File "/code/./app/main.py", line 120, in startup_event
2023-02-21T05:19:03Z   [info]    database.recreate_collection(
2023-02-21T05:19:03Z   [info]  File "/usr/local/lib/python3.9/site-packages/qdrant_client/qdrant_client.py", line 1609, in recreate_collection
2023-02-21T05:19:03Z   [info]    self.delete_collection(collection_name)
2023-02-21T05:19:03Z   [info]  File "/usr/local/lib/python3.9/site-packages/qdrant_client/qdrant_client.py", line 1543, in delete_collection
2023-02-21T05:19:03Z   [info]    result: Optional[bool] = self.http.collections_api.delete_collection(
2023-02-21T05:19:03Z   [info]  File "/usr/local/lib/python3.9/site-packages/qdrant_client/http/api/collections_api.py", line 788, in delete_collection
2023-02-21T05:19:03Z   [info]    return self._build_for_delete_collection(
2023-02-21T05:19:03Z   [info]  File "/usr/local/lib/python3.9/site-packages/qdrant_client/http/api/collections_api.py", line 268, in _build_for_delete_collection
2023-02-21T05:19:03Z   [info]    return self.api_client.request(
2023-02-21T05:19:03Z   [info]  File "/usr/local/lib/python3.9/site-packages/qdrant_client/http/api_client.py", line 68, in request
2023-02-21T05:19:03Z   [info]    return self.send(request, type_)
2023-02-21T05:19:03Z   [info]  File "/usr/local/lib/python3.9/site-packages/qdrant_client/http/api_client.py", line 85, in send
2023-02-21T05:19:03Z   [info]    response = self.middleware(request, self.send_inner)
2023-02-21T05:19:03Z   [info]  File "/usr/local/lib/python3.9/site-packages/qdrant_client/http/api_client.py", line 188, in __call__
2023-02-21T05:19:03Z   [info]    return call_next(request)
2023-02-21T05:19:03Z   [info]  File "/usr/local/lib/python3.9/site-packages/qdrant_client/http/api_client.py", line 97, in send_inner
2023-02-21T05:19:03Z   [info]    raise ResponseHandlingException(e)
2023-02-21T05:19:03Z   [info]qdrant_client.http.exceptions.ResponseHandlingException: [Errno -2] Name or service not known
2023-02-21T05:19:03Z   [info]ERROR:    Application startup failed. Exiting.
2023-02-21T05:19:04Z   [info]Starting clean up.
```

Any help would be greatly appreciated!

**Comment by monatis** [comment]
Hi @cyrilzakka, could you please try passing the host value without any HTTP prefix? e.g., `*.aws.cloud.qdrant.io`

**Comment by monatis** [comment]
I don't have Fly experience, but does it allow traffic to external addresses? Some providers may limit external networking to only standard ports, e.g., on 80 and 443 but not on 6333. Tif was the case with Huggingface Spaces, for example.

**Comment by monatis** [comment]
Unfortunately, Qdrant Cloud listens only on ports 6333 (REST) and 6334 (gRPC) at the moment. I'll report this internally and return back to you wen we have any update in this. Thanks for reporting!

**Comment by generall** [comment]
Sorry, second attempt to look into it ;)

In your log you got

```
2023-02-21T06:19:38Z   [info]b'{"error":"key doesn\'t exist"}'
```

Which means that the API key you were using is removed or belong to some other cluster. Could you please check it, @cyrilzakka ?

**Comment by generall** [comment]
@cyrilzakka Are you using using 6333 port?

The response `2023-02-21T06:19:38Z   [info]b'{"error":"key doesn\'t exist"}'` is coming from our cloud, so that means that connection is working.

**Comment by generall** [comment]
I am trying to reproduce that, but it looks like fty.io servers are not available for me:

```
generall@pop-os ~/p/v/t/f/hello-fly (main)> fly launch --now
An existing fly.toml file was found for app throbbing-paper-9008
? Would you like to copy its configuration to the new app? No
Creating app in /home/generall/projects/vector_search/tmp/fly/hello-fly
Scanning source code
Detected a Dockerfile app
? Choose an app name (leave blank to generate one): 
automatically selected personal organization: Andrey Vasnetsov
? Choose a region for deployment: Amsterdam, Netherlands (ams)
Created app red-pine-7865 in organization personal
Admin URL: https://fly.io/apps/red-pine-7865
Hostname: red-pine-7865.fly.dev
Wrote config file fly.toml
==> Building image
Remote builder fly-builder-throbbing-tree-133 ready
==> Creating build context
--> Creating build context done
==> Building image with Docker
--> docker host: 20.10.12 linux x86_64
Sending build context to Docker daemon  9.115kB
[+] Building 815.7s (1/1) FINISHED                                                                                                                                                                                                        
 => ERROR [internal] load remote build context                                                                                                                                                                                     815.7s
------
 > [internal] load remote build context:
------
Error failed to fetch an image or build from source: error building: error during connect: Post "http://[fdaa:1:69f5:a7b:c6ef:ab82:e3c9:2]:2375/v1.41/build?buildargs=null&buildid=upload-request%3A2e6062d4b74638d2e4a93670576e4fe48a35c5ecf6659a6c094b6d2bfc3a6ccb&cachefrom=null&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=&labels=null&memory=0&memswap=0&networkmode=&rm=0&shmsize=0&target=&ulimits=null&version=2": EOF

```

**Comment by kylemclaren** [comment]
@cyrilzakka Check out https://github.com/kylemclaren/qdrant-on-fly to bootstrap a Qdrant cluster on Fly in a sensible way. 

From there, you can use the `.internal` address to access the app from your client. But if you need to access Qdrant from outside Fly, then allocate a public IP.

So in the Python client:

### Private
```python
client = QdrantClient(url='<FLY_APP_NAME>.internal:6333', api_key="<YOUR_API_KEY>")
```

### Public
```python
client = QdrantClient(url='<FLY_APP_NAME>.fly.dev:443', api_key="<YOUR_API_KEY>")
```

Note that the above examples exclude the protocol (ie. `http`/`https`)

**Comment by joein** [comment]
Going to close this due to inactivity, feel free to reopen the issue
