### ISSUE TITLE
Persisting high-dimensional vectors in QdrantLocal

### ISSUE THREAD

**Issue by joein** [qdrant/qdrant-client#166]
We have problems with persisting of high-dimensional vectors in QdrantLocal
If we try to save vectors with dimensionality >= 433, it fails (see traceback in the bottom)

We also don't properly close db in `LocalCollection`

I read some sources about dbm or shelve (shelve is a layer on top of dbm which provides interface to store values in any format) and there were written, that these modules work with fairly small values. 
[dbm docs](https://docs.python.org/3/library/dbm.html) (look for `Warning` in the bottom of the page)
[shelve docs](https://docs.python.org/3/library/shelve.html#restrictions)
[blog](https://www.zachburchill.ml/scraping_problems/#fnref:4) (some guy also encountered NegativeSize exception)

Code snippet to reproduce:

```Python
import random
import numpy as np
import qdrant_client
import qdrant_client.http.models as rest

default_collection_name = "example"
qdrant_args = {"path": "qdrant"}


def ingest_data(vector_size=433):  # vector_size < 433: works, vector_size >= 433: crashes
    lines = [x for x in range(10)]
    embeddings = np.random.randn(len(lines), vector_size).tolist()
    client = qdrant_client.QdrantClient(**qdrant_args)
    client.recreate_collection(default_collection_name, vectors_config=rest.VectorParams(
                size=vector_size,
                distance=rest.Distance.COSINE,
            ),)
    client.upsert(
        collection_name=default_collection_name,
        points=rest.Batch.construct(
            ids=[random.randint(0, 100) for _ in range(len(lines))],
            vectors=embeddings,
        )
    )


if __name__ == '__main__':
    ingest_data()
    ingest_data()  # Crashes here. Here we have the second instance

```

Traceback
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/qdrant/qdrant-local-issue/raw.py", line 29, in <module>
    ingest_data()
  File "/Users/qdrant/qdrant-local-issue/raw.py", line 13, in ingest_data
    client = qdrant_client.QdrantClient(**qdrant_args)
  File "/Users/qdrant/qdrant-local-issue/venv/lib/python3.8/site-packages/qdrant_client/qdrant_client.py", line 80, in __init__
    self._client = QdrantLocal(location=path)
  File "/Users/qdrant/qdrant-local-issue/venv/lib/python3.8/site-packages/qdrant_client/local/qdrant_local.py", line 39, in __init__
    self._load()
  File "/Users/qdrant/qdrant-local-issue/venv/lib/python3.8/site-packages/qdrant_client/local/qdrant_local.py", line 55, in _load
    self.collections[collection_name] = LocalCollection(config, collection_path)
  File "/Users/qdrant/qdrant-local-issue/venv/lib/python3.8/site-packages/qdrant_client/local/local_collection.py", line 48, in __init__
    self.load()
  File "/Users/qdrant/qdrant-local-issue/venv/lib/python3.8/site-packages/qdrant_client/local/local_collection.py", line 53, in load
    for idx, point in enumerate(self.storage.load()):
  File "/Users/qdrant/qdrant-local-issue/venv/lib/python3.8/site-packages/qdrant_client/local/persistence.py", line 52, in load
    for key in self.storage.keys():
SystemError: Negative size passed to PyBytes_FromStringAndSize
```

**Comment by Alw3ys** [comment]
Thanks for opening this issue with a more narrow example on how to reproduce
