### ISSUE TITLE
Error "cannot convert to json number" when using gRPC to upsert points

### ISSUE THREAD

**Issue by jbp35** [qdrant/qdrant-client#267]
I am trying to batch upsert chunks of points using qdrant client to a Qdrant Cloud instance. It works fine without gRPC but takes a long time. 

When I set prefer_grpc=True to try to speed up the operation, I get a StatusCode.INVALID_ARGUMENT error - "cannot convert to json number". 

Here is the traceback:

```
Traceback (most recent call last):
  File "/workspaces/boamp/parser_boamp_v2.py", line 36, in <module>
    main()
  File "/workspaces/boamp/parser_boamp_v2.py", line 31, in main
    list_points = qdrantAPI.merge_output(df)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/boamp/tasks/qdrantAPI.py", line 40, in merge_output
    upload_chunk(list_points)
  File "/workspaces/boamp/tasks/qdrantAPI.py", line 63, in upload_chunk
    qdrant.upsert(
  File "/home/vscode/.local/lib/python3.11/site-packages/qdrant_client/qdrant_client.py", line 757, in upsert
    return self._client.upsert(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/qdrant_client/qdrant_remote.py", line 1097, in upsert
    grpc_result = self.grpc_points.Upsert(
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/grpc/_channel.py", line 1161, in __call__
    return _end_unary_response_blocking(state, call, False, None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/grpc/_channel.py", line 1004, in _end_unary_response_blocking
    raise _InactiveRpcError(state)  # pytype: disable=not-instantiable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.INVALID_ARGUMENT
        details = "cannot convert to json number"
        debug_error_string = "UNKNOWN:Error received from peer ipv4:34.231.36.208:6334 {grpc_message:"cannot convert to json number", grpc_status:3, created_time:"2023-08-23T08:52:22.298748674+00:00"}"
>
```

Here is the config of my collection:

```
{
    "result": {
        "status": "green",
        "optimizer_status": "ok",
        "vectors_count": 0,
        "indexed_vectors_count": 0,
        "points_count": 0,
        "segments_count": 2,
        "config": {
            "params": {
                "vectors": {
                    "size": 1536,
                    "distance": "Cosine"
                },
                "shard_number": 1,
                "replication_factor": 1,
                "write_consistency_factor": 1,
                "on_disk_payload": true
            },
            "hnsw_config": {
                "m": 16,
                "ef_construct": 100,
                "full_scan_threshold": 10000,
                "max_indexing_threads": 0,
                "on_disk": false
            },
            "optimizer_config": {
                "deleted_threshold": 0.2,
                "vacuum_min_vector_number": 1000,
                "default_segment_number": 0,
                "max_segment_size": null,
                "memmap_threshold": null,
                "indexing_threshold": 20000,
                "flush_interval_sec": 5,
                "max_optimization_threads": 1
            },
            "wal_config": {
                "wal_capacity_mb": 32,
                "wal_segments_ahead": 0
            },
            "quantization_config": null
        },
        "payload_schema": {}
    },
    "status": "ok",
    "time": 0.000017428
}
```

I also tried locally with a docker image and get the same error in the console:

`2023-08-23 17:30:27 [2023-08-23T15:30:27.508Z INFO  qdrant::tonic::logging] gRPC /qdrant.Points/Upsert failed with Client specified an invalid argument "cannot convert to json number" 0.037779`

Any idea how to address this issue?

**Comment by jbp35** [comment]
I figured the problem: I am using pandas.to_dict to generate the payload and my dataframe contains NaN values. Replacing NaN values by None values in the dataframe fix the issue.

```
import numpy as np
import pandas as pd

df = df.replace({np.nan: None})
```

**Comment by jbp35** [comment]
I figured the problem: I am using pandas.to_dict to generate the payload and my dataframe contains NaN values. Replacing NaN values by None values in the dataframe fix the issue.

```
import numpy as np
import pandas as pd

df = df.replace({np.nan: None})
```
