### ISSUE TITLE
qdrant-client metadata headers not working in 1.5.0

### ISSUE THREAD

**Issue by MathiasSpanhove** [qdrant/qdrant-client#291]
The following snippet of code doesn't work anymore:

```python
client = qdrant_client.QdrantClient(
    url=f"{QDRANT_APP_URL}",
    port=443,
    timeout=120,
    metadata={"Authorization": f"Bearer {token}"},
)
```

and results in the following exception:

```
Traceback (most recent call last):
  File "D:\Programming\qdrant-haystack\examples\test2.py", line 19, in <module>
    client = qdrant_client.QdrantClient(
  File "D:\Programming\qdrant-haystack\.venv\lib\site-packages\qdrant_client\qdrant_client.py", line 77, in __init__
    super().__init__(**kwargs)
  File "D:\Programming\qdrant-haystack\.venv\lib\site-packages\qdrant_client\qdrant_fastembed.py", line 38, in __init__
    super().__init__(**kwargs)
TypeError: object.__init__() takes exactly one argument (the instance to initialize)
```

Removing the kwargs from the `super().__init__()` in `QdrantFastembedMixin` seems to fix the issue:

```python
class QdrantFastembedMixin(QdrantBase):
    DEFAULT_EMBEDDING_MODEL = "BAAI/bge-small-en"

    embedding_models: Dict[str, "DefaultEmbedding"] = {}

    def __init__(self, **kwargs: Any):
        self.embedding_model_name = self.DEFAULT_EMBEDDING_MODEL
        super().__init__() # remove the **kwargs
```

Related: https://github.com/qdrant/qdrant-haystack/issues/30

**Comment by generall** [comment]
@MathiasSpanhove, please try v1.5.4
