### ISSUE TITLE
unknown variant `WriteOrdering.STRONG`

### ISSUE THREAD

**Issue by tekumara** [qdrant/qdrant-client#320]
When using:
```python
from qdrant_client import QdrantClient, models
from qdrant_client.conversions import common_types as types

...

    qdrant_client.batch_update_points(
        collection_name=COLLECTION_NAME,
        update_operations=ops,
        wait=True,
        ordering=types.WriteOrdering.STRONG,
    )
```    

```
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.12_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/homebrew/Cellar/python@3.10/3.10.12_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/tekumara/code/qdrant-demo/demo/race.py", line 84, in <module>
    main()
  File "/Users/tekumara/code/qdrant-demo/demo/race.py", line 70, in main
    qdrant_client.batch_update_points(
  File "/Users/tekumara/code/qdrant-demo/.venv/lib/python3.10/site-packages/qdrant_client/qdrant_client.py", line 1185, in batch_update_points
    return self._client.batch_update_points(
  File "/Users/tekumara/code/qdrant-demo/.venv/lib/python3.10/site-packages/qdrant_client/qdrant_remote.py", line 1512, in batch_update_points
    result: Optional[types.UpdateResult] = self.openapi_client.points_api.batch_update(
  File "/Users/tekumara/code/qdrant-demo/.venv/lib/python3.10/site-packages/qdrant_client/http/api/points_api.py", line 963, in batch_update
    return self._build_for_batch_update(
  File "/Users/tekumara/code/qdrant-demo/.venv/lib/python3.10/site-packages/qdrant_client/http/api/points_api.py", line 65, in _build_for_batch_update
    return self.api_client.request(
  File "/Users/tekumara/code/qdrant-demo/.venv/lib/python3.10/site-packages/qdrant_client/http/api_client.py", line 74, in request
    return self.send(request, type_)
  File "/Users/tekumara/code/qdrant-demo/.venv/lib/python3.10/site-packages/qdrant_client/http/api_client.py", line 97, in send
    raise UnexpectedResponse.for_response(response)
qdrant_client.http.exceptions.UnexpectedResponse: Unexpected Response: 400 (Bad Request)
Raw response content:
b'{"status":{"error":"Deserialize error in query parameters: unknown variant `WriteOrdering.STRONG`, expected one of `weak`, `medium`, `strong`"},"time":0.0}'
```

qdrant server 1.5.1
qdrant-client==1.5.4

**Comment by tekumara** [comment]
From the server logs:
```
qdrant-1 qdrant 2023-09-30T08:57:38.574254Z  INFO actix_web::middleware::logger: 10.42.0.60 "POST /collections/birds/points/batch?wait=true&ordering=WriteOrdering.STRONG HTTP/1.1" 400 148 "-" "python-httpx/0.25.0" 0.000265    
```

**Comment by joein** [comment]
I believe should be fixed as of qdrant-client==1.6.0
