### ISSUE TITLE
create_payload_index fails on gRPC when field_schema is set

### ISSUE THREAD

**Issue by felipebcs** [qdrant/qdrant-client#379]
Hi guys. I've tried to create a payload index using `create_payload_index`, but it fails when gRPC is enabled and `field_schema='integer'`. When `prefer_grpc=False`, the rest connection works as expected.

```python
external_id_field_name = 'eid'
external_id_field_type = 'integer' 

qdrant.create_payload_index(
	collection_name=collection_name,
	field_name=external_id_field_name,
	field_schema=external_id_field_type,
	wait=True,
)
```

This gives:
```bash
Error: Traceback (most recent call last):
...
File "/home/ray/.local/lib/python3.8/site-packages/qdrant_client/qdrant_client.py", line 1625, in create_payload_index
 return self._client.create_payload_index(
File "/home/ray/.local/lib/python3.8/site-packages/qdrant_client/qdrant_remote.py", line 1975, in create_payload_index
 request = grpc.CreateFieldIndexCollection(
ValueError: unknown enum label "integer"

```

Is there another way to specify the field type when using gRPC connections?

-----
Running qdrant version is `1.6.1`, `qdrant_client==1.6.9`

**Comment by joein** [comment]
Hello,

At the moment you can use 

```python
from qdrant_client.models import models


external_id_field_type = models.PayloadSchemaType.INTEGER
...
```

**Comment by felipebcs** [comment]
Thanks, @joein! Using `models.PayloadSchemaType.INTEGER` did the trick
