### ISSUE TITLE
grpc error when searching using langchain

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [qdrant/qdrant-client#404]
Dear all,

I have a qdrant client

```python
import os

from qdrant_client import QdrantClient


def get_vector_db() -> QdrantClient:
    host = os.environ["VECTOR_DB_HOST"]
    port = os.environ["VECTOR_DB_PORT"]
    # 'vectordb' is host name when running all services with docker-compose up
    https = not host.startswith("localhost") and host != "vectordb"
    client = QdrantClient(host=host, port=port, https=https)

    return client
```
In prod, we had to do that weird conditioning because `qdrant` don't set `https` automatically when you pass a `url` with `https`

then I use is with langchain

```python
....
self._db = Qdrant(
            client=get_vector_db(),
            collection_name=collection_name,
            embeddings=self._embeddings,
        )

self._chain = ConversationalRetrievalChain.from_llm(
    self._llm,
    retriever=self._db.as_retriever(),
    return_source_documents=True,
    verbose=True,
)

...

When I search

```python
 await chain.acall({"question": question, "chat_history": chat_history})
```

I got

```bash
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 274, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/services/api/routers/api/rag/route.py", line 109, in get_answer
    answer, sources = await qa.get_answer_with_retriever(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/services/api/services/qa.py", line 102, in get_answer_with_retriever
    return await self._get_answer(self._chain, question, chat_history, k, filter)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/services/api/services/qa.py", line 79, in _get_answer
    res = await chain.acall({"question": question, "chat_history": chat_history})
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/langchain/chains/base.py", line 377, in acall
    raise e
  File "/usr/local/lib/python3.11/site-packages/langchain/chains/base.py", line 371, in acall
    await self._acall(inputs, run_manager=run_manager)
  File "/usr/local/lib/python3.11/site-packages/langchain/chains/conversational_retrieval/base.py", line 198, in _acall
    docs = await self._aget_docs(new_question, inputs, run_manager=_run_manager)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/langchain/chains/conversational_retrieval/base.py", line 316, in _aget_docs
    docs = await self.retriever.aget_relevant_documents(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/langchain/schema/retriever.py", line 269, in aget_relevant_documents
    raise e
  File "/usr/local/lib/python3.11/site-packages/langchain/schema/retriever.py", line 262, in aget_relevant_documents
    result = await self._aget_relevant_documents(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/langchain/schema/vectorstore.py", line 605, in _aget_relevant_documents
    docs = await self.vectorstore.asimilarity_search(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/langchain/vectorstores/qdrant.py", line 55, in wrapper
    return await method(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/langchain/vectorstores/qdrant.py", line 302, in asimilarity_search
    results = await self.asimilarity_search_with_score(query, k, filter, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/langchain/vectorstores/qdrant.py", line 55, in wrapper
    return await method(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/langchain/vectorstores/qdrant.py", line 408, in asimilarity_search_with_score
    return await self.asimilarity_search_with_score_by_vector(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/langchain/vectorstores/qdrant.py", line 55, in wrapper
    return await method(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/langchain/vectorstores/qdrant.py", line 715, in asimilarity_search_with_score_by_vector
    response = await self._asearch_with_score_by_vector(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/langchain/vectorstores/qdrant.py", line 650, in _asearch_with_score_by_vector
    response = await self.client.async_grpc_points.Search(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/grpc/aio/_call.py", line 318, in __await__
    raise _create_rpc_error(
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:10.217.237.154:6334: Failed to connect to remote host: FD Shutdown"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2023-12-13T08:54:23.186589333+00:00", grpc_status:14, grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:10.217.237.154:6334: Failed to connect to remote host: FD Shutdown"}"
>
```

**Note** qdrant is only running on the http port, I don't get it why is using grpc, is this a langchain issue?

**Comment by Priyalakshmi7** [comment]
We are trying with deployed URL (https),but couldn't able to create a collection.
Almost getting the same error @FrancescoSaverioZuppichini .Have you got any solution to resolve this error?

Here is our code,
```from qdrant_client import QdrantClient
from qdrant_client.http.models import Distance, VectorParams
qdrant_client = QdrantClient(
    url=server_url,
    port=6333,
    prefer_grpc=True,
    grpc_port=6334,
    https=True,
    api_key=qdrant_api_key,
   
)
qdrant_client.create_collection(
    collection_name="my_collection_test",
    vectors_config=VectorParams(size=100, distance=Distance.COSINE),
)
print("Collection created.")```

**Comment by joein** [comment]
Hi @FrancescoSaverioZuppichini 

> Note qdrant is only running on the http port, I don't get it why is using grpc, is this a langchain issue?

We hadn't had a proper async support for the rest client a while ago, so async qdrant client used to use grpc in langchain.
As far as I know, now it should already have both options (rest and grpc), version upgrade may help

> In prod, we had to do that weird conditioning because qdrant don't set https automatically when you pass a url with https

`host` parameter is not supposed to have scheme in it, but when using `url` and passing `https` scheme, it should work. We are trying to figure out this problem with you in another issue :)

**Comment by joein** [comment]
@Priyalakshmi7 hello, could you please share your traceback?

**Comment by joein** [comment]
Btw, @FrancescoSaverioZuppichini 

This error `Failed to connect to remote host: FD Shutdown` might mean that there are some firewalls or proxies which prevents the client from reaching the service, can it be the case?
