### ISSUE TITLE
Default qdrant deployment config requires to add any `api_key` otherwise it fails

### ISSUE THREAD

**Issue by vemonet** [qdrant/qdrant-client#437]
Trying to run Qdrant with docker and access it from a public URL does not work. Accessing directly from the docker network host works though

So I deployed Qdrant without setting any security. And try to connect with:

```python
vectordb = QdrantClient(
    host=qdrant_url,
    port=443,
)
```

## Current Behavior

When I run my script I am getting this error:

```
Traceback (most recent call last):
  File "/home/vemonet/dev/llm/concept-resolver/src/pubdict_load.py", line 76, in <module>
    vectordb.recreate_collection(
  File "/home/vemonet/dev/llm/concept-resolver/.venv/lib/python3.10/site-packages/qdrant_client/qdrant_client.py", line 1751, in recreate_collection
    return self._client.recreate_collection(
  File "/home/vemonet/dev/llm/concept-resolver/.venv/lib/python3.10/site-packages/qdrant_client/qdrant_remote.py", line 2181, in recreate_collection
    self.delete_collection(collection_name, timeout=timeout)
  File "/home/vemonet/dev/llm/concept-resolver/.venv/lib/python3.10/site-packages/qdrant_client/qdrant_remote.py", line 2049, in delete_collection
    result: Optional[bool] = self.http.collections_api.delete_collection(
  File "/home/vemonet/dev/llm/concept-resolver/.venv/lib/python3.10/site-packages/qdrant_client/http/api/collections_api.py", line 1189, in delete_collection
    return self._build_for_delete_collection(
  File "/home/vemonet/dev/llm/concept-resolver/.venv/lib/python3.10/site-packages/qdrant_client/http/api/collections_api.py", line 239, in _build_for_delete_collection
    return self.api_client.request(
  File "/home/vemonet/dev/llm/concept-resolver/.venv/lib/python3.10/site-packages/qdrant_client/http/api_client.py", line 74, in request
    return self.send(request, type_)
  File "/home/vemonet/dev/llm/concept-resolver/.venv/lib/python3.10/site-packages/qdrant_client/http/api_client.py", line 97, in send
    raise UnexpectedResponse.for_response(response)
qdrant_client.http.exceptions.UnexpectedResponse: Unexpected Response: 400 (Bad Request)
Raw response content:
b'<html>\r\n<head><title>400 The plain HTTP request was sent to HTTPS port</title></head>\r\n<body>\r\n<center><h1>400 Bad Request</h1></center>\r\n<center>The plain HTTP request was sent to HTTPS port</cent ...'
```

If I change my code to add any API key:

```bash
vectordb = QdrantClient(
    host=qdrant_url,
    port=443,
    api_key="MAMAMIA",
)
```

The `QdrantClient` instantiation passes without error. But when I `upsert` I get:

```
Traceback (most recent call last):
  File "/home/vemonet/dev/llm/concept-resolver/.venv/lib/python3.10/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
    yield
  File "/home/vemonet/dev/llm/concept-resolver/.venv/lib/python3.10/site-packages/httpcore/_backends/sync.py", line 136, in write
    n = self._sock.send(buffer)
  File "/usr/lib/python3.10/ssl.py", line 1235, in send
    return self._sslobj.write(data)
TimeoutError: The write operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/vemonet/dev/llm/concept-resolver/.venv/lib/python3.10/site-packages/httpx/_transports/default.py", line 67, in map_httpcore_exceptions
    yield
  File "/home/vemonet/dev/llm/concept-resolver/.venv/lib/python3.10/site-packages/httpx/_transports/default.py", line 231, in handle_request
    resp = self._pool.handle_request(req)
  File "/home/vemonet/dev/llm/concept-resolver/.venv/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 268, in handle_request
    raise exc
  File "/home/vemonet/dev/llm/concept-resolver/.venv/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 251, in handle_request
    response = connection.handle_request(request)
  File "/home/vemonet/dev/llm/concept-resolver/.venv/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 103, in handle_request
    return self._connection.handle_request(request)
  File "/home/vemonet/dev/llm/concept-resolver/.venv/lib/python3.10/site-packages/httpcore/_sync/http11.py", line 133, in handle_request
    raise exc
  File "/home/vemonet/dev/llm/concept-resolver/.venv/lib/python3.10/site-packages/httpcore/_sync/http11.py", line 94, in handle_request
    self._send_request_body(**kwargs)
  File "/home/vemonet/dev/llm/concept-resolver/.venv/lib/python3.10/site-packages/httpcore/_sync/http11.py", line 156, in _send_request_body
    self._send_event(event, timeout=timeout)
  File "/home/vemonet/dev/llm/concept-resolver/.venv/lib/python3.10/site-packages/httpcore/_sync/http11.py", line 165, in _send_event
    self._network_stream.write(bytes_to_send, timeout=timeout)
  File "/home/vemonet/dev/llm/concept-resolver/.venv/lib/python3.10/site-packages/httpcore/_backends/sync.py", line 133, in write
    with map_exceptions(exc_map):
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/vemonet/dev/llm/concept-resolver/.venv/lib/python3.10/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.WriteTimeout: The write operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/vemonet/dev/llm/concept-resolver/.venv/lib/python3.10/site-packages/qdrant_client/http/api_client.py", line 101, in send_inner
    response = self._client.send(request)
  File "/home/vemonet/dev/llm/concept-resolver/.venv/lib/python3.10/site-packages/httpx/_client.py", line 915, in send
    response = self._send_handling_auth(
  File "/home/vemonet/dev/llm/concept-resolver/.venv/lib/python3.10/site-packages/httpx/_client.py", line 943, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/home/vemonet/dev/llm/concept-resolver/.venv/lib/python3.10/site-packages/httpx/_client.py", line 980, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/home/vemonet/dev/llm/concept-resolver/.venv/lib/python3.10/site-packages/httpx/_client.py", line 1016, in _send_single_request
    response = transport.handle_request(request)
  File "/home/vemonet/dev/llm/concept-resolver/.venv/lib/python3.10/site-packages/httpx/_transports/default.py", line 230, in handle_request
    with map_httpcore_exceptions():
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/vemonet/dev/llm/concept-resolver/.venv/lib/python3.10/site-packages/httpx/_transports/default.py", line 84, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.WriteTimeout: The write operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vemonet/dev/llm/concept-resolver/src/pubdict_load.py", line 112, in <module>
    vectordb.upsert(
  File "/home/vemonet/dev/llm/concept-resolver/.venv/lib/python3.10/site-packages/qdrant_client/qdrant_client.py", line 987, in upsert
    return self._client.upsert(
  File "/home/vemonet/dev/llm/concept-resolver/.venv/lib/python3.10/site-packages/qdrant_client/qdrant_remote.py", line 1300, in upsert
    http_result = self.openapi_client.points_api.upsert_points(
  File "/home/vemonet/dev/llm/concept-resolver/.venv/lib/python3.10/site-packages/qdrant_client/http/api/points_api.py", line 1439, in upsert_points
    return self._build_for_upsert_points(
  File "/home/vemonet/dev/llm/concept-resolver/.venv/lib/python3.10/site-packages/qdrant_client/http/api/points_api.py", line 738, in _build_for_upsert_points
    return self.api_client.request(
  File "/home/vemonet/dev/llm/concept-resolver/.venv/lib/python3.10/site-packages/qdrant_client/http/api_client.py", line 74, in request
    return self.send(request, type_)
  File "/home/vemonet/dev/llm/concept-resolver/.venv/lib/python3.10/site-packages/qdrant_client/http/api_client.py", line 91, in send
    response = self.middleware(request, self.send_inner)
  File "/home/vemonet/dev/llm/concept-resolver/.venv/lib/python3.10/site-packages/qdrant_client/http/api_client.py", line 200, in __call__
    return call_next(request)
  File "/home/vemonet/dev/llm/concept-resolver/.venv/lib/python3.10/site-packages/qdrant_client/http/api_client.py", line 103, in send_inner
    raise ResponseHandlingException(e)
qdrant_client.http.exceptions.ResponseHandlingException: The write operation timed out
```

If I use the internal docker host and query qdrant from a container on the same docker network it works completely:

```python
vectordb = QdrantClient(
    host="qdrant",
    port=6333,
)
```

It also works if I use grpc:

```python
vectordb = QdrantClient(
    host="qdrant",
    port=6333,
    prefer_grpc=True,
)
```

## Steps to Reproduce

1. Docker compose here: https://github.com/vemonet/concept-resolver/blob/main/docker-compose.yml
2. Python code here: https://github.com/vemonet/concept-resolver/blob/main/src/pubdict_load.py

## Expected Behavior

I am not sure what is going on here to be honest

But I should be able to upsert to the public HTTPS URL, and I should not need to add an API key to instantiate the QdrantClient if no security are set. 

Otherwise error messages should be clearer

**Comment by vemonet** [comment]
I am also getting the same error when using `url=https://` instead of `host`

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vemonet/dev/llm/concept-resolver/src/babel_load.py", line 39, in <module>
    vectordb.recreate_collection(
  File "/home/vemonet/dev/llm/concept-resolver/.venv/lib/python3.10/site-packages/qdrant_client/qdrant_client.py", line 1751, in recreate_collection
    return self._client.recreate_collection(
  File "/home/vemonet/dev/llm/concept-resolver/.venv/lib/python3.10/site-packages/qdrant_client/qdrant_remote.py", line 2181, in recreate_collection
    self.delete_collection(collection_name, timeout=timeout)
  File "/home/vemonet/dev/llm/concept-resolver/.venv/lib/python3.10/site-packages/qdrant_client/qdrant_remote.py", line 2049, in delete_collection
    result: Optional[bool] = self.http.collections_api.delete_collection(
  File "/home/vemonet/dev/llm/concept-resolver/.venv/lib/python3.10/site-packages/qdrant_client/http/api/collections_api.py", line 1189, in delete_collection
    return self._build_for_delete_collection(
  File "/home/vemonet/dev/llm/concept-resolver/.venv/lib/python3.10/site-packages/qdrant_client/http/api/collections_api.py", line 239, in _build_for_delete_collection
    return self.api_client.request(
  File "/home/vemonet/dev/llm/concept-resolver/.venv/lib/python3.10/site-packages/qdrant_client/http/api_client.py", line 74, in request
    return self.send(request, type_)
  File "/home/vemonet/dev/llm/concept-resolver/.venv/lib/python3.10/site-packages/qdrant_client/http/api_client.py", line 91, in send
    response = self.middleware(request, self.send_inner)
  File "/home/vemonet/dev/llm/concept-resolver/.venv/lib/python3.10/site-packages/qdrant_client/http/api_client.py", line 200, in __call__
    return call_next(request)
  File "/home/vemonet/dev/llm/concept-resolver/.venv/lib/python3.10/site-packages/qdrant_client/http/api_client.py", line 103, in send_inner
    raise ResponseHandlingException(e)
qdrant_client.http.exceptions.ResponseHandlingException: timed out
```

I think the issue is coming from the proxy of the server where we have deployed the service

But finally for this specific project we moved to pgvector since there is already a postgres in the stack

Thanks!

**Comment by timvisee** [comment]
> I think the issue is coming from the proxy of the server where we have deployed the service

If your proxy is not transparent, then that's definitely what might have been going on.

>     b'<html>\r\n<head><title>400 The plain HTTP request was sent to HTTPS port</title></head>\r\n<body>\r\n<center><h1>400 Bad Request</h1></center>\r\n<center>The plain HTTP request was sent to HTTPS port</cent ...'

This shows a HTTP/HTTPS mix-up.

Depending on how you set up your client, you must be able to talk HTTP(S) and/or gRPC through your proxy.

Let us know if we can be of any further help. :smile:
