### ISSUE TITLE
investigate local mode close

### ISSUE THREAD

**Issue by joein** [qdrant/qdrant-client#514]
found in tests:
```  
Traceback (most recent call last):
    File "/home/runner/work/qdrant-client/qdrant-client/qdrant_client/qdrant_client.py", line 132, in __del__
      self.close()
    File "/home/runner/work/qdrant-client/qdrant-client/qdrant_client/qdrant_client.py", line 141, in close
      self._client.close(grpc_grace=grpc_grace, **kwargs)
    File "/home/runner/work/qdrant-client/qdrant-client/qdrant_client/local/qdrant_local.py", line 78, in close
      portalocker.unlock(self._flock_file)
    File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/portalocker/portalocker.py", line 114, in unlock
      fcntl.flock(file_.fileno(), LockFlags.UNBLOCK)
  ValueError: I/O operation on closed file
```

**Comment by joein** [comment]
#521
