### ISSUE TITLE
sys:1: RuntimeWarning: coroutine 'PointsStub.upsert' was never awaited

### ISSUE THREAD

**Issue by kulame** [qdrant/qdrant-client#60]
i try to run upsert in async function.

```python 
async def upsert(client, path):
    gen_filename(path)
    kind = filetype.guess(path)
    debug(kind.extension)
    debug(kind.mime)
    np = face_recognition.load_image_file(path)
    vector = face_recognition.face_encodings(np)[0]
    client.upsert(
        collection_name="pig",
        points=[
            models.PointStruct(
                id=1,
                payload={
                    "filename": path,
                },
                vector=vector.tolist(),
            ),
        ]
    )


async def main():
    load_dotenv()

    client = QdrantClient(host="localhost",
                          grpc_port=6334, prefer_grpc=True)

    await upsert(client, "images/1.jpg")

if __name__ == "__main__":
    asyncio.run(main())

```

it raise  Exception 

```python
Traceback (most recent call last):
  File "/srv/project/face/main.py", line 61, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/srv/project/face/main.py", line 57, in main
    await upsert(client, "images/1.jpg")
  File "/srv/project/face/main.py", line 37, in upsert
    client.upsert(
  File "/home/kula/.cache/pypoetry/virtualenvs/face-G3AFUNPz-py3.10/lib/python3.10/site-packages/qdrant_client/qdrant_client.py", line 566, in upsert
    asyncio.get_event_loop().run_until_complete(self._grpc_points_client.upsert(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 622, in run_until_complete
    self._check_running()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 582, in _check_running
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
sys:1: RuntimeWarning: coroutine 'PointsStub.upsert' was never awaited
```

does it compatible with async function?

qdrant-client = "^0.9.0"

**Comment by generall** [comment]
You might want to look at `client.grpc_collections` &`client.grpc_points` directly, those classes provide async versions of functions directly.

**Comment by kulame** [comment]
i changed client.upsert to  client.grpc_points.upsert, 
but  it raise exception 
```
  File "/srv/project/face/main.py", line 60, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/srv/project/face/main.py", line 57, in main
    await upsert(client, "images/1.jpg")
  File "/srv/project/face/main.py", line 37, in upsert
    await client.grpc_points.upsert(
  File "/home/kula/.cache/pypoetry/virtualenvs/face-G3AFUNPz-py3.10/lib/python3.10/site-packages/qdrant_client/grpc/__init__.py", line 859, in upsert
    return await self._unary_unary(
  File "/home/kula/.cache/pypoetry/virtualenvs/face-G3AFUNPz-py3.10/lib/python3.10/site-packages/betterproto/grpc/grpclib_client.py", line 79, in _unary_unary
    await stream.send_message(request, end=True)
  File "/home/kula/.cache/pypoetry/virtualenvs/face-G3AFUNPz-py3.10/lib/python3.10/site-packages/grpclib/client.py", line 255, in send_message
    await send_message(self._stream, self._codec, message,
  File "/home/kula/.cache/pypoetry/virtualenvs/face-G3AFUNPz-py3.10/lib/python3.10/site-packages/grpclib/stream.py", line 44, in send_message
    reply_bin = codec.encode(message, message_type)
  File "/home/kula/.cache/pypoetry/virtualenvs/face-G3AFUNPz-py3.10/lib/python3.10/site-packages/grpclib/encoding/proto.py", line 47, in encode
    return message.SerializeToString()
  File "/home/kula/.cache/pypoetry/virtualenvs/face-G3AFUNPz-py3.10/lib/python3.10/site-packages/betterproto/__init__.py", line 840, in SerializeToString
    return bytes(self)
  File "/home/kula/.cache/pypoetry/virtualenvs/face-G3AFUNPz-py3.10/lib/python3.10/site-packages/betterproto/__init__.py", line 786, in __bytes__
    _serialize_single(
  File "/home/kula/.cache/pypoetry/virtualenvs/face-G3AFUNPz-py3.10/lib/python3.10/site-packages/betterproto/__init__.py", line 396, in _serialize_single
    value = _preprocess_single(proto_type, wraps, value)
  File "/home/kula/.cache/pypoetry/virtualenvs/face-G3AFUNPz-py3.10/lib/python3.10/site-packages/betterproto/__init__.py", line 382, in _preprocess_single
    return bytes(value)
TypeError: 'tuple' object cannot be interpreted as an integer
Exception ignored in: <function QdrantClient.__del__ at 0x7f7bf5cd6830>
Traceback (most recent call last):
  File "/home/kula/.cache/pypoetry/virtualenvs/face-G3AFUNPz-py3.10/lib/python3.10/site-packages/qdrant_client/qdrant_client.py", line 73, in __del__
  File "/home/kula/.cache/pypoetry/virtualenvs/face-G3AFUNPz-py3.10/lib/python3.10/site-packages/grpclib/client.py", line 787, in close
  File "/home/kula/.cache/pypoetry/virtualenvs/face-G3AFUNPz-py3.10/lib/python3.10/site-packages/grpclib/protocol.py", line 554, in close
  File "/home/kula/.cache/pypoetry/virtualenvs/face-G3AFUNPz-py3.10/lib/python3.10/site-packages/grpclib/protocol.py", line 234, in close
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 697, in close
  File "/usr/lib/python3.10/asyncio/base_events.py", line 750, in call_soon
  File "/usr/lib/python3.10/asyncio/base_events.py", line 515, in _check_closed
RuntimeError: Event loop is closed
```

does any grpc_points example for me?

**Comment by dgcnz** [comment]
Are there any plans of implementing an asynchronous QdrantClient? Using the raw grpc client isn't too bad, but it would be nice to have typehints

**Comment by joein** [comment]
Since of `qdrant-client==1.1.7` async grpc endpoints were exposed

You can use it with `await client.async_grpc_collections.<method>(...) or await client.async_grpc_points.<method>(...)`

Feel free to re-open the issue or ask a question in our [Discord](https://discord.com/channels/907569970500743200/928649303898075196) in case of any other problems
