### ISSUE TITLE
Python got an issue using filter with not indexed payload field using client with URL and api_key.

### ISSUE THREAD

**Issue by justynas-amlyze** [qdrant/qdrant-client#607]
Linux Fedora 39.
Python got an issue using filter with not indexed payload field using client with URL and api_key.
I get it only using URL, when I'm using k8s port forward host=localhost no issue.

Client:
`qdrant_client  = AsyncQdrantClient(url=QDRANT_URL, port=QDRANT_PORT, api_key=QDRANT_KEY)`

Error:
```
Traceback (most recent call last):
  File "/home/justynas/scripts/py/venv-3.11.8/lib64/python3.11/site-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
    yield
  File "/home/justynas/scripts/py/venv-3.11.8/lib64/python3.11/site-packages/httpx/_transports/default.py", line 373, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/justynas/scripts/py/venv-3.11.8/lib64/python3.11/site-packages/httpcore/_async/connection_pool.py", line 216, in handle_async_request
    raise exc from None
  File "/home/justynas/scripts/py/venv-3.11.8/lib64/python3.11/site-packages/httpcore/_async/connection_pool.py", line 196, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/justynas/scripts/py/venv-3.11.8/lib64/python3.11/site-packages/httpcore/_async/connection.py", line 101, in handle_async_request
    return await self._connection.handle_async_request(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/justynas/scripts/py/venv-3.11.8/lib64/python3.11/site-packages/httpcore/_async/http11.py", line 143, in handle_async_request
    raise exc
  File "/home/justynas/scripts/py/venv-3.11.8/lib64/python3.11/site-packages/httpcore/_async/http11.py", line 113, in handle_async_request
    ) = await self._receive_response_headers(**kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/justynas/scripts/py/venv-3.11.8/lib64/python3.11/site-packages/httpcore/_async/http11.py", line 186, in _receive_response_headers
    event = await self._receive_event(timeout=timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/justynas/scripts/py/venv-3.11.8/lib64/python3.11/site-packages/httpcore/_async/http11.py", line 224, in _receive_event
    data = await self._network_stream.read(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/justynas/scripts/py/venv-3.11.8/lib64/python3.11/site-packages/httpcore/_backends/anyio.py", line 31, in read
    with map_exceptions(exc_map):
  File "/usr/lib64/python3.11/contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/justynas/scripts/py/venv-3.11.8/lib64/python3.11/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ReadTimeout

```

**Comment by joein** [comment]
hi @justynas-amlyze 

could you try increasing timeout?

however, search with filters without the corresponding payload indices is discouraged, and timeouts are possible, since without payload indices it is just a brute-force filtering

**Comment by justynas-amlyze** [comment]
Yes, my bad I just switched from grpc and I didn't check regarding timeout. Newbie mistake :)
cheers :)
