### ISSUE TITLE
Ssl handshake failed

### ISSUE THREAD

**Issue by tekumara** [qdrant/qdrant-client#770]
```
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1725536788.069320 12131471 ssl_transport_security.cc:1654] Handshake failed with fatal error SSL_ERROR_SSL: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER
E0000 00:00:1725536788.336742 12131479 ssl_transport_security.cc:1654] Handshake failed with fatal error SSL_ERROR_SSL: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.14/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/homebrew/Cellar/python@3.10/3.10.14/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/tekumara/code/qdrant-demo/src/demo/download.py", line 86, in <module>
    main()
  File "/Users/tekumara/code/qdrant-demo/src/demo/download.py", line 80, in main
    payloads = download_payloads(qc, args.collection_name, args.limit, args.batch_size)
  File "/Users/tekumara/code/qdrant-demo/src/demo/download.py", line 23, in download_payloads
    search_result, next_offset = qc.scroll(
  File "/Users/tekumara/code/qdrant-demo/.venv/lib/python3.10/site-packages/qdrant_client/qdrant_client.py", line 1094, in scroll
    return self._client.scroll(
  File "/Users/tekumara/code/qdrant-demo/.venv/lib/python3.10/site-packages/qdrant_client/qdrant_remote.py", line 1406, in scroll
    res: grpc.ScrollResponse = self.grpc_points.Scroll(
  File "/Users/tekumara/code/qdrant-demo/.venv/lib/python3.10/site-packages/grpc/_interceptor.py", line 277, in __call__
    response, ignored_call = self._with_call(
  File "/Users/tekumara/code/qdrant-demo/.venv/lib/python3.10/site-packages/grpc/_interceptor.py", line 332, in _with_call
    return call.result(), call
  File "/Users/tekumara/code/qdrant-demo/.venv/lib/python3.10/site-packages/grpc/_channel.py", line 440, in result
    raise self
  File "/Users/tekumara/code/qdrant-demo/.venv/lib/python3.10/site-packages/grpc/_interceptor.py", line 315, in continuation
    response, call = self._thunk(new_method).with_call(
  File "/Users/tekumara/code/qdrant-demo/.venv/lib/python3.10/site-packages/grpc/_channel.py", line 1198, in with_call
    return _end_unary_response_blocking(state, call, True, None)
  File "/Users/tekumara/code/qdrant-demo/.venv/lib/python3.10/site-packages/grpc/_channel.py", line 1006, in _end_unary_response_blocking
    raise _InactiveRpcError(state)  # pytype: disable=not-instantiable
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:6334: Ssl handshake failed (TSI_PROTOCOL_FAILURE): SSL_ERROR_SSL: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER"
        debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:6334: Ssl handshake failed (TSI_PROTOCOL_FAILURE): SSL_ERROR_SSL: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER", grpc_status:14, created_time:"2024-09-05T21:46:28.338722+10:00"}"
```

qdrant-client==1.10.0
grpcio==1.66.1
grpcio-tools==1.66.1

qdrant server 1.7.3

**Comment by oxffaa** [comment]
Hello!

I have the same problem.

Log:
`I0000 00:00:1753266526.530264   22308 ssl_transport_security.cc:1756] Handshake failed with error SSL_ERROR_SSL: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER: Invalid certificate verification context
I0000 00:00:1753266526.532853   22306 ssl_transport_security.cc:1756] Handshake failed with error SSL_ERROR_SSL: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER: Invalid certificate verification context
I0000 00:00:1753266527.664410   22315 ssl_transport_security.cc:1756] Handshake failed with error SSL_ERROR_SSL: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER: Invalid certificate verification context
I0000 00:00:1753266527.694052   22309 ssl_transport_security.cc:1756] Handshake failed with error SSL_ERROR_SSL: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER: Invalid certificate verification context
I0000 00:00:1753266528.993598   22302 ssl_transport_security.cc:1756] Handshake failed with error SSL_ERROR_SSL: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER: Invalid certificate verification context
I0000 00:00:1753266529.066036   22308 ssl_transport_security.cc:1756] Handshake failed with error SSL_ERROR_SSL: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER: Invalid certificate verification context
I0000 00:00:1753266531.439548   22315 ssl_transport_security.cc:1756] Handshake failed with error SSL_ERROR_SSL: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER: Invalid certificate verification context
I0000 00:00:1753266531.442799   22305 ssl_transport_security.cc:1756] Handshake failed with error SSL_ERROR_SSL: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER: Invalid certificate verification context
I0000 00:00:1753266535.147179   22310 ssl_transport_security.cc:1756] Handshake failed with error SSL_ERROR_SSL: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER: Invalid certificate verification context
I0000 00:00:1753266536.216106   22309 ssl_transport_security.cc:1756] Handshake failed with error SSL_ERROR_SSL: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER: Invalid certificate verification context
I0000 00:00:1753266540.996300   22306 ssl_transport_security.cc:1756] Handshake failed with error SSL_ERROR_SSL: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER: Invalid certificate verification context
I0000 00:00:1753266541.703093   22308 ssl_transport_security.cc:1756] Handshake failed with error SSL_ERROR_SSL: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER: Invalid certificate verification context
I0000 00:00:1753266551.352625   22302 ssl_transport_security.cc:1756] Handshake failed with error SSL_ERROR_SSL: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER: Invalid certificate verification context
I0000 00:00:1753266552.960575   22312 ssl_transport_security.cc:1756] Handshake failed with error SSL_ERROR_SSL: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER: Invalid certificate verification context
I0000 00:00:1753266568.228537   22305 ssl_transport_security.cc:1756] Handshake failed with error SSL_ERROR_SSL: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER: Invalid certificate verification context
I0000 00:00:1753266568.327454   22303 ssl_transport_security.cc:1756] Handshake failed with error SSL_ERROR_SSL: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER: Invalid certificate verification context
I0000 00:00:1753266593.217088   22302 ssl_transport_security.cc:1756] Handshake failed with error SSL_ERROR_SSL: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER: Invalid certificate verification context
I0000 00:00:1753266594.032924   22311 ssl_transport_security.cc:1756] Handshake failed with error SSL_ERROR_SSL: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER: Invalid certificate verification context
I0000 00:00:1753266629.152646   22304 ssl_transport_security.cc:1756] Handshake failed with error SSL_ERROR_SSL: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER: Invalid certificate verification context
I0000 00:00:1753266640.981854   22311 ssl_transport_security.cc:1756] Handshake failed with error SSL_ERROR_SSL: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER: Invalid certificate verification context
I0000 00:00:1753266685.775199   22310 ssl_transport_security.cc:1756] Handshake failed with error SSL_ERROR_SSL: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER: Invalid certificate verification context
I0000 00:00:1753266710.249376   22308 ssl_transport_security.cc:1756] Handshake failed with error SSL_ERROR_SSL: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER: Invalid certificate verification context
I0000 00:00:1753266788.639030   22302 ssl_transport_security.cc:1756] Handshake failed with error SSL_ERROR_SSL: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER: Invalid certificate verification context
I0000 00:00:1753266819.568013   22309 ssl_transport_security.cc:1756] Handshake failed with error SSL_ERROR_SSL: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER: Invalid certificate verification context
I0000 00:00:1753266921.389107   22312 ssl_transport_security.cc:1756] Handshake failed with error SSL_ERROR_SSL: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER: Invalid certificate verification context
I0000 00:00:1753266922.499325   22313 ssl_transport_security.cc:1756] Handshake failed with error SSL_ERROR_SSL: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER: Invalid certificate verification context
I0000 00:00:1753267030.827704   22313 ssl_transport_security.cc:1756] Handshake failed with error SSL_ERROR_SSL: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER: Invalid certificate verification context
I0000 00:00:1753267064.867981   22303 ssl_transport_security.cc:1756] Handshake failed with error SSL_ERROR_SSL: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER: Invalid certificate verification context
I0000 00:00:1753267153.306338   22308 ssl_transport_security.cc:1756] Handshake failed with error SSL_ERROR_SSL: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER: Invalid certificate verification context
I0000 00:00:1753267178.464731   22308 ssl_transport_security.cc:1756] Handshake failed with error SSL_ERROR_SSL: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER: Invalid certificate verification context
I0000 00:00:1753267282.514654   22309 ssl_transport_security.cc:1756] Handshake failed with error SSL_ERROR_SSL: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER: Invalid certificate verification context
I0000 00:00:1753267300.223538   22311 ssl_transport_security.cc:1756] Handshake failed with error SSL_ERROR_SSL: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER: Invalid certificate verification context
I0000 00:00:1753267389.526300   22310 ssl_transport_security.cc:1756] Handshake failed with error SSL_ERROR_SSL: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER: Invalid certificate verification context
I0000 00:00:1753267435.622010   22308 ssl_transport_security.cc:1756] Handshake failed with error SSL_ERROR_SSL: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER: Invalid certificate verification context`

"qdrant-client>=1.15.0"
"grpcio==1.73.1"
qdrant server 1.7.0

**Comment by erhhung** [comment]
@oxffaa Thanks for the test script, which I've shamelessly used to test my Kubernetes deployment of the Qdrant cluster with config options `server.enable_tls=true` and `cluster.p2p.enable_tls=true` and `tls.cert`/`tls.key`/`tls.ca_cert` set to certificate issued by a private CA.

```python
import logging
import asyncio
import socket
import ssl
from qdrant_client import AsyncQdrantClient

logging.basicConfig(level=logging.DEBUG)

QDRANT_HOST = "qdrant.qdrant.svc.cluster.local"

async def check_tls_versions():
    print("=== SSL/TLS Information ===")
    print(f"OpenSSL version: {ssl.OPENSSL_VERSION}")
    print(f"Available protocols: {[p for p in dir(ssl) if p.startswith('PROTOCOL_')]}")

    context = ssl.create_default_context()
    print(f"Default SSL context protocol: {context.protocol}")
    print(f"Minimum TLS version: {context.minimum_version}")
    print(f"Maximum TLS version: {context.maximum_version}")

    print("\n=== Testing TLS Connection to Qdrant ===")

    try:
        print("1. Testing direct TLS connection...")
        sock = socket.create_connection((QDRANT_HOST, 6334), timeout=10)
        ssl_sock = context.wrap_socket(sock, server_hostname=QDRANT_HOST)

        print(f"✅ TLS connection successful!")
        print(f"TLS version: {ssl_sock.version()}")
        print(f"Cipher: {ssl_sock.cipher()}")
        print(f"Server certificate: {ssl_sock.getpeercert()}")
        ssl_sock.close()

    except Exception as e:
        print(f"❌ Direct TLS connection failed: {e}")

    try:
        print("\n2. Testing Qdrant gRPC client...")
        client = AsyncQdrantClient(
            host=QDRANT_HOST,
            port=6334,
            prefer_grpc=True,
            https=True,
            timeout=10,
        )
        collections = await client.get_collections()
        print(f"✅ Qdrant gRPC successful! Collections: {len(collections.collections)}")
        await client.close()

    except Exception as e:
        print(f"❌ Qdrant gRPC failed: {e}")

    try:
        print("\n3. Testing Qdrant HTTPS client...")
        client = AsyncQdrantClient(
            host=QDRANT_HOST,
            port=6333,
            prefer_grpc=False,
            https=False,
            timeout=10,
        )
        collections = await client.get_collections()
        print(f"✅ Qdrant HTTPS successful! Collections: {len(collections.collections)}")
        await client.close()

    except Exception as e:
        print(f"❌ Qdrant HTTPS failed: {e}")

if __name__ == "__main__":
    asyncio.run(check_tls_versions())
```

```
$ python3 ssltest.py
DEBUG:asyncio:Using selector: EpollSelector
=== SSL/TLS Information ===
OpenSSL version: OpenSSL 3.2.2 4 Jun 2024
Available protocols: ['PROTOCOL_SSLv23', 'PROTOCOL_TLS', 'PROTOCOL_TLS_CLIENT', 'PROTOCOL_TLS_SERVER', 'PROTOCOL_TLSv1', 'PROTOCOL_TLSv1_1', 'PROTOCOL_TLSv1_2']
Default SSL context protocol: 16
Minimum TLS version: 771
Maximum TLS version: 772

=== Testing TLS Connection to Qdrant ===
1. Testing direct TLS connection...
❌ Direct TLS connection failed: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1028)

2. Testing Qdrant gRPC client...
DEBUG:httpcore.connection:connect_tcp.started host='qdrant.qdrant.svc.cluster.local' port=6334 local_address=None timeout=5.0 socket_options=None
DEBUG:httpcore.connection:connect_tcp.complete return_value=<httpcore._backends.sync.SyncStream object at 0x7aaed5753770>
DEBUG:httpcore.connection:start_tls.started ssl_context=<ssl.SSLContext object at 0x7aaed57027b0> server_hostname='qdrant.qdrant.svc.cluster.local' timeout=5.0
DEBUG:httpcore.connection:start_tls.failed exception=ConnectError(SSLError(1, '[SSL] tlsv1 alert no application protocol (_ssl.c:1028)'))
DEBUG:root:Unable to get server version: [SSL] tlsv1 alert no application protocol (_ssl.c:1028), server version defaults to None
DEBUG:grpc._cython.cygrpc:Using AsyncIOEngine.POLLER as I/O engine
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1754212510.028063     171 ssl_transport_security.cc:1756] Handshake failed with error SSL_ERROR_SSL:
error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate
❌ Qdrant gRPC failed: <AioRpcError of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:10.43.61.201:6334:
Ssl handshake failed (TSI_PROTOCOL_FAILURE):
SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate"
        debug_error_string = "UNKNOWN:Error received from peer  {grpc_status:14, grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:10.43.61.201:6334:
Ssl handshake failed (TSI_PROTOCOL_FAILURE):
SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate"}"

3. Testing Qdrant HTTPS client...
DEBUG:httpcore.connection:connect_tcp.started host='qdrant.qdrant.svc.cluster.local' port=6333 local_address=None timeout=5.0 socket_options=None
DEBUG:httpcore.connection:connect_tcp.complete return_value=<httpcore._backends.sync.SyncStream object at 0x7aaed5466210>
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'GET']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'GET']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'GET']>
DEBUG:httpcore.http11:receive_response_headers.failed exception=RemoteProtocolError(RemoteProtocolError('illegal request line'))
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:root:Unable to get server version: illegal request line, server version defaults to None
DEBUG:httpcore.connection:connect_tcp.started host='qdrant.qdrant.svc.cluster.local' port=6333 local_address=None timeout=10 socket_options=None
DEBUG:httpcore.connection:connect_tcp.complete return_value=<httpcore._backends.anyio.AnyIOStream object at 0x7aaed5480c20>
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'GET']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'GET']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'GET']>
DEBUG:httpcore.http11:receive_response_headers.failed exception=RemoteProtocolError(RemoteProtocolError('illegal request line'))
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
❌ Qdrant HTTPS failed: illegal request line
```

I don't see a parameter in the `QdrantClient` constructor that would either allow specifying a path to custom `cacert.pem` file, or disable certificate validation altogether.

I see in the `get_channel()` function in [`connection.py`](https://github.com/qdrant/qdrant-client/blob/master/qdrant_client/connection.py#L270):

```python
    if ssl:
        ssl_creds = grpc.ssl_channel_credentials()
        channel = grpc.secure_channel(f"{host}:{port}", ssl_creds, _options, compression)
        return grpc.intercept_channel(channel, metadata_interceptor)
```

`grpc.ssl_channel_credentials()` with no parameters given uses no custom CA certs for verification. Somehow, the API needs to be able to accept a `ca_cert_file` parameter and do:

```python
if ca_cert_file:
    with open(ca_cert_file, 'rb') as f:
        ca_cert_data = f.read()

ssl_creds = grpc.ssl_channel_credentials(root_certificates=ca_cert_data)
channel = grpc.secure_channel(f"{host}:{port}", ssl_creds, _options, compression)
```

**Comment by erhhung** [comment]
Well, okay, there is at least a workaround to the `CERTIFICATE_VERIFY_FAILED` error, which is to use the underlying gRPC library's support for specifying the default trust store using an [environment variable](https://grpc.github.io/grpc/core/md_doc_environment_variables.html):

```bash
export GRPC_DEFAULT_SSL_ROOTS_FILE_PATH=/path/to/private/ca.crt
```
